apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app-deployment
  labels:
    app: maven-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
      - name: maven-app-container
        image: abhradippaul/maven-devsecops:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          cpu: 50m
          memory: 100Mi
