apiVersion: v1
kind: Service
metadata:
  labels:
    app: maven-app
  name: maven-app-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
  selector:
    app: maven-app
  type: NodePort
